apiVersion: v1
kind: ServiceAccount
metadata:
  name: trigger-bot
  namespace: ks-devops-ext
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trigger-binding
  namespace: ks-devops-ext
subjects:
  - kind: ServiceAccount
    name: trigger-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trigger-clusterbinding
  namespace: ks-devops-ext
subjects:
  - kind: ServiceAccount
    name: trigger-bot
    namespace: ks-devops-ext
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
