apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ks-versions
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubesphere-sigs/ks-versions
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ks-version
  syncPolicy:
    automated:
      prune: true
